#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

echo $DAPPER_SOURCE

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"
CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o bin/terraform-controller
