#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

cp bin/terraform-controller package/
cp bin/terraform-controller dist/artifacts/terraform-controller${SUFFIX}

cd package

IMAGE=${REPO}/terraform-controller:${TAG}
docker build -t ${IMAGE} -f Dockerfile.controller .
echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}
