#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

mkdir ./yaml
cp ../manifests/*.yaml ./yaml

IMAGE=${REPO}/terraform-controller-appliance:${TAG}
docker build -t ${IMAGE} -f Dockerfile.appliance .
echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}

rm -rf ./yaml
