#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

cp bin/terraform-executor package/
cp bin/terraform-executor dist/artifacts/terraform-executor${SUFFIX}

cd package

IMAGE=${REPO}/terraform-controller-executor:${TAG}
docker build -t ${IMAGE} -f Dockerfile.executor .
echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}
