#!/bin/bash
set -e

if ! hash helm 2>/dev/null; then
    exit 0
fi

source $(dirname $0)/version

cd $(dirname $0)/..

rm -rf build/chart
mkdir -p build
cp -rf chart build/

sed -i \
    -e 's/version:.*/version: '${HELM_VERSION}'/' \
    -e 's/appVersion:.*/appVersion: '${HELM_VERSION}'/' \
    build/chart/Chart.yaml

sed -i \
    -e 's/tag: ${VERSION}/tag: '${HELM_TAG}'/' \
    build/chart/values.yaml

helm package -d ./dist/artifacts ./build/chart
