#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

cp ../bin/terraform-executor .

IMAGE=${REPO}/terraform-controller-executor:${TAG}
docker build -t ${IMAGE} -f Dockerfile.executor .
echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}
