#!/bin/bash

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

SUFFIX="-${ARCH}"

HELM_TAG=${GIT_TAG:-v0.0.0+${VERSION}}
HELM_VERSION=${HELM_TAG/v/}
TAG=${GIT_TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $GIT_TAG | grep -q dirty; then
    TAG=dev
    HELM_TAG=v0.0.0+${COMMIT}
    HELM_VERSION=v0.0.0
fi
